### ISSUE TITLE
I have tried using many forks of trape, and It doesn't switch on

### ISSUE THREAD

**Issue by skandabhairava** [FullPenetrationTesting/trape#1]
Ngrok and the access key for the control panel doesn't work
OS: Windows 10

When trying to use access key, it just displays a "Method not allowed" screen
And this is what happens to ngrok,
![Screenshot 2022-02-27 142226](https://user-images.githubusercontent.com/58636952/155875559-a796eb89-ff06-4ccb-87e5-6a49a0f9587b.jpg)

**Comment by FullPenetrationTesting** [comment]
try to forward port manually...
